---
version: "3.9"
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus:/etc/prometheus
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    links:
      - prometheus