scala_library(
    name = "aoc2023",
    srcs = glob(["*.scala"], exclude=["Day6.scala"]),
    deps = [
        "//src/main/scala/aoc",
    ],
    visibility = [
        "//visibility:public",
    ],
    resources = [
        "//src/main/resources/aoc2023:day1.input",
        "//src/main/resources/aoc2023:day2.input",
        "//src/main/resources/aoc2023:day3.input",
        "//src/main/resources/aoc2023:day4.input",
        "//src/main/resources/aoc2023:day5.input",
        "//src/main/resources/aoc2023:day7.input",
        "//src/main/resources/aoc2023:day8.input",
        "//src/main/resources/aoc2023:day9.input",
    ]
)

advent_of_code_binary(
    name = 'Day6',
    main_class = "aoc2023.Day6Main",
    input_file = "//src/main/resources/aoc2023:day6.input",
)

advent_of_code_binary(
    name = 'Day9',
    main_class = "aoc2023.Day9Main",
    input_file = "//src/main/resources/aoc2023:day9.input",
)

advent_of_code_binary(
    name = 'Day10',
    main_class = "aoc2023.Day10Main",
    input_file = "//src/main/resources/aoc2023:day10.input",
)

advent_of_code_binary(
    name = 'Day11',
    main_class = "aoc2023.Day11Main",
    input_file = "//src/main/resources/aoc2023:day11.input",
)
