scala_library(
    name = "aoc2023",
    srcs = glob(["*.scala"]),
    deps = [
        "//src/main/scala/aoc",
    ],
    visibility = [
        "//visibility:public",
    ],
    resources = [
        "//src/main/resources/aoc2023:day1.input",
        "//src/main/resources/aoc2023:day2.input",
    ]
)
