scala_library(
    name = "aoc2022",
    srcs = glob(["*.scala"]),
    deps = [
        "//src/main/scala/aoc"
    ],
    visibility = [
        "//visibility:public",
    ],
    resources = [
        "//src/main/resources/aoc2022:day16.input",
    ]
)
